stages:
- runall
- build
- collate

# This is just a config to help trigger rest of the builds
run_all_builds:
  image: ubuntu:latest
  stage: runall
  variables:
    GIT_STRATEGY: none
  script:
  - pwd
  when: manual
  allow_failure: false

# Build
build_osx_runtime:
  stage: build
  tags:
    - buildfarm
    - darwin
  script:
  - git submodule update --init --recursive
  - echo -e "[auth]\nono.schemes=https\nono.prefix=ono.unity3d.com\nono.username=$GITLAB_UNITY_META_ONO_USER\nono.password=$GITLAB_UNITY_META_ONO_PASS\n" >> ~/.hgrc
  - perl external/buildscripts/build_runtime_osx.pl
  artifacts:
    paths:
    - builds
    expire_in: 1 week
# Important! Do not remove this after_script!!  
  after_script:
    - /opt/post_build_script.sh

build_osx_classlibs:
  stage: build
  tags:
    - buildfarm
    - darwin
  script:
  - git submodule update --init --recursive
  - echo -e "[auth]\nono.schemes=https\nono.prefix=ono.unity3d.com\nono.username=$GITLAB_UNITY_META_ONO_USER\nono.password=$GITLAB_UNITY_META_ONO_PASS\n" >> ~/.hgrc
  - perl external/buildscripts/build_classlibs_osx.pl
  artifacts:
    paths:
    - builds
    expire_in: 1 week
# Important! Do not remove this after_script!!  
  after_script:
    - /opt/post_build_script.sh

build_android:
  stage: build
  tags:
    - buildfarm
    - darwin
  script:
  - git submodule update --init --recursive
  - echo -e "[auth]\nono.schemes=https\nono.prefix=ono.unity3d.com\nono.username=$GITLAB_UNITY_META_ONO_USER\nono.password=$GITLAB_UNITY_META_ONO_PASS\n" >> ~/.hgrc
  - bash external/buildscripts/build_runtime_android.sh
  artifacts:
    paths:
    - builds
    expire_in: 1 week
# Important! Do not remove this after_script!!  
  after_script:
    - /opt/post_build_script.sh

build_win:
  stage: build
  tags:
  - buildfarm
  - windows
  script:
  - git submodule update --init --recursive
  - perl external/buildscripts/build_runtime_win64.pl
  artifacts:
    paths:
    - builds
    expire_in: 1 week
# Important! Do not remove this after_script!!
  after_script:
    - C:\Users\builduser\post_build_script.bat

build_win_x86:
  stage: build
  tags:
  - buildfarm
  - windows
  script:
  - git submodule update --init --recursive
  - perl external/buildscripts/build_runtime_win.pl
  artifacts:
    paths:
    - builds
    expire_in: 1 week
# Important! Do not remove this after_script!!
  after_script:
    - C:\Users\builduser\post_build_script.bat

build_win_bare_minimum:
  stage: build
  tags:
  - buildfarm
  - windows
  script:
  - git submodule update --init --recursive
  - perl external/buildscripts/build_unityscript_bareminimum_win.pl
  artifacts:
    paths:
    - builds
    expire_in: 1 week
# Important! Do not remove this after_script!!
  after_script:
    - C:\Users\builduser\post_build_script.bat

build_linux_x64:
  stage: build
  tags:
  - buildfarm
  - linux
  script:
  - git submodule update --init --recursive
  - echo -e "[auth]\nono.schemes=https\nono.prefix=ono.unity3d.com\nono.username=$GITLAB_UNITY_META_ONO_USER\nono.password=$GITLAB_UNITY_META_ONO_PASS\n" >> ~/.hgrc
  - perl external/buildscripts/build_runtime_linux.pl -build64=1
  artifacts:
    paths:
    - builds
    expire_in: 1 week
# Important! Do not remove this after_script!!  
  after_script:
    - /opt/post_build_script.sh

build_linux_x86:
  stage: build
  tags:
  - buildfarm
  - linux
  dependencies:
  - run_all_builds
  script:
  - git submodule update --init --recursive
  - echo -e "[auth]\nono.schemes=https\nono.prefix=ono.unity3d.com\nono.username=$GITLAB_UNITY_META_ONO_USER\nono.password=$GITLAB_UNITY_META_ONO_PASS\n" >> ~/.hgrc
  - perl external/buildscripts/build_runtime_linux.pl
  artifacts:
    paths:
    - builds
    expire_in: 1 week
# Important! Do not remove this after_script!!  
  after_script:
    - /opt/post_build_script.sh

collate_builds:
  image: ubuntu:latest
  stage: collate
  dependencies:
  - build_osx_runtime
  - build_osx_classlibs
  - build_win
  - build_win_x86
  - build_win_bare_minimum
  - build_linux_x86
  - build_linux_x64
  before_script:
  - apt-get update -qy && apt-get -qy upgrade
  - apt-get install -qy perl
  - apt-get install -qy zip unzip
  script:
  - perl external/buildscripts/collect_allbuilds.pl